// ============================================================
//  idiomas.js — Traducciones Hotel Las Quenas
//  Detección automática por idioma del navegador
// ============================================================

const TRADUCCIONES = {
  es: {
    bienvenida: "Bienvenido/a",
    donde_tradicion: "Donde la Tradición encuentra el Lujo.",
    comenzar_checkin: "COMENZAR PRE CHECK-IN",
    sin_filas: "Solo 3 minutos · Sin filas en recepción",
    reserva_confirmada: "Reserva confirmada",
    registro_huespedes: "Registro de Huéspedes",
    complete_datos: "Complete los datos de todos los que le acompañan.",
    huesped_principal: "Huésped Principal",
    titular_reserva: "Titular de la reserva",
    nombre_completo: "Nombre Completo",
    email: "Email",
    pais: "País / Código",
    telefono: "Teléfono",
    contacto_preferido: "Contacto Preferido",
    tipo_documento: "Tipo de Documento",
    nro_documento: "Número de Documento",
    foto_anverso: "Foto del Documento — Frente (Anverso)",
    foto_reverso: "Foto del Documento — Reverso",
    foto_pasaporte: "Foto del Pasaporte",
    toca_fotografiar: "Toca para fotografiar",
    optimizada_avif: "La imagen se optimizará a formato AVIF automáticamente",
    anadir_acompanante: "Añadir otro acompañante",
    continuar: "CONTINUAR",
    paso_registro: "Paso 2 de 5 · Registro de huéspedes",
    detalles_llegada: "Detalles de su Llegada",
    medio_transporte: "¿Cómo llegará a Cusco?",
    vuelo: "Vuelo",
    bus: "Bus / Empresa de transporte",
    auto: "Auto propio",
    fecha_llegada: "Fecha de Llegada",
    aerolinea: "Aerolínea",
    empresa_bus: "Empresa de Bus",
    nro_vuelo: "Número de Vuelo",
    hora_estimada: "Hora Estimada de Llegada",
    sin_codigo: "No se necesita código para este medio de transporte",
    tours_titulo: "Experiencias en Cusco",
    tours_subtitulo: "¿Qué tours te interesan?",
    notas: "Notas Especiales o Requerimientos",
    notas_placeholder: "Ej. Alergias, silla de ruedas, celebración especial...",
    confirmar: "Confirmar Registro",
    revisar: "Revise su información antes de enviar.",
    enviar: "CONFIRMAR Y ENVIAR",
    exito_titulo: "¡Registro Completado!",
    exito_msg: "Hemos recibido su información. Su habitación estará lista antes de su llegada.",
    codigo_reserva: "Código de Reserva",
    contactar_hotel: "Contactar al Hotel por WhatsApp",
    adulto: "Adulto",
    nino: "Niño/a",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Llamada",
    soroche_titulo: "Consejo sobre el Soroche",
    soroche_msg: "Cusco está a 3,399 metros de altura. Recomendamos descansar las primeras horas, hidratarse con nuestro mate de coca y evitar comidas pesadas.",
  },
  en: {
    bienvenida: "Welcome",
    donde_tradicion: "Where Tradition meets Luxury.",
    comenzar_checkin: "START PRE CHECK-IN",
    sin_filas: "Only 3 minutes · Skip the reception queue",
    reserva_confirmada: "Booking confirmed",
    registro_huespedes: "Guest Registration",
    complete_datos: "Please fill in the details for all guests in your group.",
    huesped_principal: "Main Guest",
    titular_reserva: "Booking holder",
    nombre_completo: "Full Name",
    email: "Email",
    pais: "Country / Code",
    telefono: "Phone",
    contacto_preferido: "Preferred Contact",
    tipo_documento: "Document Type",
    nro_documento: "Document Number",
    foto_anverso: "Document Photo — Front",
    foto_reverso: "Document Photo — Back",
    foto_pasaporte: "Passport Photo",
    toca_fotografiar: "Tap to photograph",
    optimizada_avif: "Image will be automatically optimized to AVIF format",
    anadir_acompanante: "Add another guest",
    continuar: "CONTINUE",
    paso_registro: "Step 2 of 5 · Guest registration",
    detalles_llegada: "Arrival Details",
    medio_transporte: "How will you arrive in Cusco?",
    vuelo: "Flight",
    bus: "Bus / Transport company",
    auto: "Own car",
    fecha_llegada: "Arrival Date",
    aerolinea: "Airline",
    empresa_bus: "Bus Company",
    nro_vuelo: "Flight Number",
    hora_estimada: "Estimated Arrival Time",
    sin_codigo: "No code needed for this transport type",
    tours_titulo: "Cusco Experiences",
    tours_subtitulo: "Which tours interest you?",
    notas: "Special Notes or Requirements",
    notas_placeholder: "E.g. Allergies, wheelchair, special celebration...",
    confirmar: "Confirm Registration",
    revisar: "Please review your information before sending.",
    enviar: "CONFIRM & SEND",
    exito_titulo: "Registration Complete!",
    exito_msg: "We received your information. Your room will be ready before your arrival.",
    codigo_reserva: "Booking Code",
    contactar_hotel: "Contact the Hotel on WhatsApp",
    adulto: "Adult",
    nino: "Child",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Phone call",
    soroche_titulo: "Altitude Sickness Advice",
    soroche_msg: "Cusco is at 3,399 metres above sea level. We recommend resting the first few hours, drinking our complimentary coca tea and avoiding heavy meals.",
  },
  pt: {
    bienvenida: "Bem-vindo/a",
    donde_tradicion: "Onde a Tradição encontra o Luxo.",
    comenzar_checkin: "INICIAR PRÉ CHECK-IN",
    sin_filas: "Apenas 3 minutos · Sem filas na recepção",
    reserva_confirmada: "Reserva confirmada",
    registro_huespedes: "Registro de Hóspedes",
    complete_datos: "Preencha os dados de todos os hóspedes do seu grupo.",
    huesped_principal: "Hóspede Principal",
    titular_reserva: "Titular da reserva",
    nombre_completo: "Nome Completo",
    email: "E-mail",
    pais: "País / Código",
    telefono: "Telefone",
    contacto_preferido: "Contato Preferido",
    tipo_documento: "Tipo de Documento",
    nro_documento: "Número do Documento",
    foto_anverso: "Foto do Documento — Frente",
    foto_reverso: "Foto do Documento — Verso",
    foto_pasaporte: "Foto do Passaporte",
    toca_fotografiar: "Toque para fotografar",
    optimizada_avif: "A imagem será otimizada automaticamente para formato AVIF",
    anadir_acompanante: "Adicionar outro hóspede",
    continuar: "CONTINUAR",
    paso_registro: "Passo 2 de 5 · Registro de hóspedes",
    detalles_llegada: "Detalhes da Chegada",
    medio_transporte: "Como chegará a Cusco?",
    vuelo: "Voo",
    bus: "Ônibus / Empresa de transporte",
    auto: "Carro próprio",
    fecha_llegada: "Data de Chegada",
    aerolinea: "Companhia Aérea",
    empresa_bus: "Empresa de Ônibus",
    nro_vuelo: "Número do Voo",
    hora_estimada: "Hora Estimada de Chegada",
    sin_codigo: "Não é necessário código para este meio de transporte",
    tours_titulo: "Experiências em Cusco",
    tours_subtitulo: "Quais tours te interessam?",
    notas: "Notas Especiais ou Requisitos",
    notas_placeholder: "Ex. Alergias, cadeira de rodas, celebração especial...",
    confirmar: "Confirmar Registro",
    revisar: "Revise suas informações antes de enviar.",
    enviar: "CONFIRMAR E ENVIAR",
    exito_titulo: "Registro Concluído!",
    exito_msg: "Recebemos suas informações. Seu quarto estará pronto antes da sua chegada.",
    codigo_reserva: "Código de Reserva",
    contactar_hotel: "Contatar o Hotel pelo WhatsApp",
    adulto: "Adulto",
    nino: "Criança",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Ligação",
    soroche_titulo: "Dica sobre o Mal de Altitude",
    soroche_msg: "Cusco está a 3.399 metros de altitude. Recomendamos descansar nas primeiras horas, hidratar-se com nosso chá de coca e evitar refeições pesadas.",
  },
  fr: {
    bienvenida: "Bienvenue",
    donde_tradicion: "Où la Tradition rencontre le Luxe.",
    comenzar_checkin: "COMMENCER LE PRÉ CHECK-IN",
    sin_filas: "Seulement 3 minutes · Sans attente à la réception",
    reserva_confirmada: "Réservation confirmée",
    registro_huespedes: "Inscription des Clients",
    complete_datos: "Veuillez remplir les informations de tous les membres de votre groupe.",
    huesped_principal: "Client Principal",
    titular_reserva: "Titulaire de la réservation",
    nombre_completo: "Nom Complet",
    email: "E-mail",
    pais: "Pays / Code",
    telefono: "Téléphone",
    contacto_preferido: "Contact Préféré",
    tipo_documento: "Type de Document",
    nro_documento: "Numéro de Document",
    foto_anverso: "Photo du Document — Recto",
    foto_reverso: "Photo du Document — Verso",
    foto_pasaporte: "Photo du Passeport",
    toca_fotografiar: "Appuyez pour photographier",
    optimizada_avif: "L'image sera automatiquement optimisée au format AVIF",
    anadir_acompanante: "Ajouter un autre client",
    continuar: "CONTINUER",
    paso_registro: "Étape 2 sur 5 · Inscription des clients",
    detalles_llegada: "Détails d'Arrivée",
    medio_transporte: "Comment arriverez-vous à Cusco ?",
    vuelo: "Vol",
    bus: "Bus / Compagnie de transport",
    auto: "Voiture personnelle",
    fecha_llegada: "Date d'Arrivée",
    aerolinea: "Compagnie Aérienne",
    empresa_bus: "Compagnie de Bus",
    nro_vuelo: "Numéro de Vol",
    hora_estimada: "Heure d'Arrivée Estimée",
    sin_codigo: "Aucun code requis pour ce moyen de transport",
    tours_titulo: "Expériences à Cusco",
    tours_subtitulo: "Quels circuits vous intéressent ?",
    notas: "Notes Spéciales ou Exigences",
    notas_placeholder: "Ex. Allergies, fauteuil roulant, célébration spéciale...",
    confirmar: "Confirmer l'Inscription",
    revisar: "Veuillez vérifier vos informations avant d'envoyer.",
    enviar: "CONFIRMER ET ENVOYER",
    exito_titulo: "Inscription Terminée !",
    exito_msg: "Nous avons reçu vos informations. Votre chambre sera prête avant votre arrivée.",
    codigo_reserva: "Code de Réservation",
    contactar_hotel: "Contacter l'Hôtel par WhatsApp",
    adulto: "Adulte",
    nino: "Enfant",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Appel téléphonique",
    soroche_titulo: "Conseil sur le Mal des Montagnes",
    soroche_msg: "Cusco est à 3 399 mètres d'altitude. Nous vous recommandons de vous reposer les premières heures, de vous hydrater avec notre thé de coca et d'éviter les repas lourds.",
  },
  de: {
    bienvenida: "Willkommen",
    donde_tradicion: "Wo Tradition auf Luxus trifft.",
    comenzar_checkin: "PRE CHECK-IN STARTEN",
    sin_filas: "Nur 3 Minuten · Kein Warten an der Rezeption",
    reserva_confirmada: "Buchung bestätigt",
    registro_huespedes: "Gästeregistrierung",
    complete_datos: "Bitte füllen Sie die Daten für alle Mitglieder Ihrer Gruppe aus.",
    huesped_principal: "Hauptgast",
    titular_reserva: "Buchungsinhaber",
    nombre_completo: "Vollständiger Name",
    email: "E-Mail",
    pais: "Land / Code",
    telefono: "Telefon",
    contacto_preferido: "Bevorzugter Kontakt",
    tipo_documento: "Dokumententyp",
    nro_documento: "Dokumentennummer",
    foto_anverso: "Dokumentenfoto — Vorderseite",
    foto_reverso: "Dokumentenfoto — Rückseite",
    foto_pasaporte: "Reisepassfoto",
    toca_fotografiar: "Zum Fotografieren tippen",
    optimizada_avif: "Das Bild wird automatisch im AVIF-Format optimiert",
    anadir_acompanante: "Weiteren Gast hinzufügen",
    continuar: "WEITER",
    paso_registro: "Schritt 2 von 5 · Gästeregistrierung",
    detalles_llegada: "Ankunftsdetails",
    medio_transporte: "Wie reisen Sie nach Cusco?",
    vuelo: "Flug",
    bus: "Bus / Transportunternehmen",
    auto: "Eigenes Auto",
    fecha_llegada: "Ankunftsdatum",
    aerolinea: "Fluggesellschaft",
    empresa_bus: "Busunternehmen",
    nro_vuelo: "Flugnummer",
    hora_estimada: "Geschätzte Ankunftszeit",
    sin_codigo: "Kein Code für dieses Transportmittel erforderlich",
    tours_titulo: "Erlebnisse in Cusco",
    tours_subtitulo: "Welche Touren interessieren Sie?",
    notas: "Besondere Hinweise oder Anforderungen",
    notas_placeholder: "Z.B. Allergien, Rollstuhl, besondere Feier...",
    confirmar: "Registrierung bestätigen",
    revisar: "Bitte überprüfen Sie Ihre Informationen vor dem Absenden.",
    enviar: "BESTÄTIGEN UND SENDEN",
    exito_titulo: "Registrierung abgeschlossen!",
    exito_msg: "Wir haben Ihre Informationen erhalten. Ihr Zimmer wird vor Ihrer Ankunft bereit sein.",
    codigo_reserva: "Buchungscode",
    contactar_hotel: "Hotel per WhatsApp kontaktieren",
    adulto: "Erwachsener",
    nino: "Kind",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Telefonanruf",
    soroche_titulo: "Hinweis zur Höhenkrankheit",
    soroche_msg: "Cusco liegt auf 3.399 Metern Höhe. Wir empfehlen, sich in den ersten Stunden zu erholen, unseren Coca-Tee zu trinken und schwere Mahlzeiten zu vermeiden.",
  },
  zh: {
    bienvenida: "欢迎",
    donde_tradicion: "传统与奢华的交汇之处。",
    comenzar_checkin: "开始预办入住",
    sin_filas: "仅需3分钟 · 无需在前台排队",
    reserva_confirmada: "预订已确认",
    registro_huespedes: "宾客登记",
    complete_datos: "请填写您所有同行人员的信息。",
    huesped_principal: "主要宾客",
    titular_reserva: "预订人",
    nombre_completo: "全名",
    email: "电子邮件",
    pais: "国家 / 区号",
    telefono: "电话",
    contacto_preferido: "首选联系方式",
    tipo_documento: "证件类型",
    nro_documento: "证件号码",
    foto_anverso: "证件照片 — 正面",
    foto_reverso: "证件照片 — 背面",
    foto_pasaporte: "护照照片",
    toca_fotografiar: "点击拍照",
    optimizada_avif: "图片将自动优化为AVIF格式",
    anadir_acompanante: "添加其他宾客",
    continuar: "继续",
    paso_registro: "第2步，共5步 · 宾客登记",
    detalles_llegada: "到达详情",
    medio_transporte: "您将如何抵达库斯科？",
    vuelo: "飞机",
    bus: "大巴 / 运输公司",
    auto: "自驾车",
    fecha_llegada: "到达日期",
    aerolinea: "航空公司",
    empresa_bus: "大巴公司",
    nro_vuelo: "航班号",
    hora_estimada: "预计到达时间",
    sin_codigo: "此交通方式无需代码",
    tours_titulo: "库斯科体验",
    tours_subtitulo: "您对哪些旅游感兴趣？",
    notas: "特殊备注或要求",
    notas_placeholder: "例如：过敏、轮椅需求、特别庆典...",
    confirmar: "确认登记",
    revisar: "发送前请检查您的信息。",
    enviar: "确认并发送",
    exito_titulo: "登记完成！",
    exito_msg: "我们已收到您的信息。您到达前，您的房间将准备就绪。",
    codigo_reserva: "预订码",
    contactar_hotel: "通过微信联系酒店",
    adulto: "成人",
    nino: "儿童",
    whatsapp: "WhatsApp",
    wechat: "微信",
    llamada: "电话",
    soroche_titulo: "高原反应提示",
    soroche_msg: "库斯科海拔3,399米。建议您最初几小时休息，饮用我们免费提供的古柯茶，避免进食过多。",
  },
  ja: {
    bienvenida: "ようこそ",
    donde_tradicion: "伝統と贅沢が出会う場所。",
    comenzar_checkin: "事前チェックインを開始",
    sin_filas: "わずか3分 · フロントでの待ち時間なし",
    reserva_confirmada: "予約確認済み",
    registro_huespedes: "ゲスト登録",
    complete_datos: "グループの全員の情報をご記入ください。",
    huesped_principal: "メインゲスト",
    titular_reserva: "予約者",
    nombre_completo: "フルネーム",
    email: "メール",
    pais: "国 / 国コード",
    telefono: "電話番号",
    contacto_preferido: "希望連絡方法",
    tipo_documento: "書類の種類",
    nro_documento: "書類番号",
    foto_anverso: "書類写真 — 表面",
    foto_reverso: "書類写真 — 裏面",
    foto_pasaporte: "パスポート写真",
    toca_fotografiar: "タップして撮影",
    optimizada_avif: "画像は自動的にAVIF形式に最適化されます",
    anadir_acompanante: "他のゲストを追加",
    continuar: "続ける",
    paso_registro: "ステップ2/5 · ゲスト登録",
    detalles_llegada: "到着詳細",
    medio_transporte: "クスコへはどのようにお越しですか？",
    vuelo: "飛行機",
    bus: "バス / 交通会社",
    auto: "自家用車",
    fecha_llegada: "到着日",
    aerolinea: "航空会社",
    empresa_bus: "バス会社",
    nro_vuelo: "フライト番号",
    hora_estimada: "到着予定時刻",
    sin_codigo: "この交通手段にはコードは不要です",
    tours_titulo: "クスコでの体験",
    tours_subtitulo: "興味のあるツアーは？",
    notas: "特別なメモや要件",
    notas_placeholder: "例：アレルギー、車椅子、特別なお祝い...",
    confirmar: "登録を確認",
    revisar: "送信前に情報をご確認ください。",
    enviar: "確認して送信",
    exito_titulo: "登録完了！",
    exito_msg: "情報を受け取りました。到着前にお部屋を準備いたします。",
    codigo_reserva: "予約コード",
    contactar_hotel: "WhatsAppでホテルに連絡",
    adulto: "大人",
    nino: "子供",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "電話",
    soroche_titulo: "高山病に関するアドバイス",
    soroche_msg: "クスコは標高3,399メートルにあります。最初の数時間は休み、コカティーを飲み、重い食事を避けることをお勧めします。",
  },
  it: {
    bienvenida: "Benvenuto/a",
    donde_tradicion: "Dove la Tradizione incontra il Lusso.",
    comenzar_checkin: "INIZIA IL PRE CHECK-IN",
    sin_filas: "Solo 3 minuti · Senza code alla reception",
    reserva_confirmada: "Prenotazione confermata",
    registro_huespedes: "Registrazione Ospiti",
    complete_datos: "Compila i dati di tutti i membri del tuo gruppo.",
    huesped_principal: "Ospite Principale",
    titular_reserva: "Titolare della prenotazione",
    nombre_completo: "Nome Completo",
    email: "E-mail",
    pais: "Paese / Prefisso",
    telefono: "Telefono",
    contacto_preferido: "Contatto Preferito",
    tipo_documento: "Tipo di Documento",
    nro_documento: "Numero di Documento",
    foto_anverso: "Foto del Documento — Fronte",
    foto_reverso: "Foto del Documento — Retro",
    foto_pasaporte: "Foto del Passaporto",
    toca_fotografiar: "Tocca per fotografare",
    optimizada_avif: "L'immagine verrà ottimizzata automaticamente in formato AVIF",
    anadir_acompanante: "Aggiungi un altro ospite",
    continuar: "CONTINUA",
    paso_registro: "Passo 2 di 5 · Registrazione ospiti",
    detalles_llegada: "Dettagli dell'Arrivo",
    medio_transporte: "Come arriverai a Cusco?",
    vuelo: "Volo",
    bus: "Autobus / Azienda di trasporto",
    auto: "Auto propria",
    fecha_llegada: "Data di Arrivo",
    aerolinea: "Compagnia Aerea",
    empresa_bus: "Azienda di Autobus",
    nro_vuelo: "Numero del Volo",
    hora_estimada: "Ora di Arrivo Stimata",
    sin_codigo: "Nessun codice necessario per questo mezzo di trasporto",
    tours_titulo: "Esperienze a Cusco",
    tours_subtitulo: "Quali tour ti interessano?",
    notas: "Note Speciali o Requisiti",
    notas_placeholder: "Es. Allergie, sedia a rotelle, celebrazione speciale...",
    confirmar: "Conferma Registrazione",
    revisar: "Controlla le tue informazioni prima di inviare.",
    enviar: "CONFERMA E INVIA",
    exito_titulo: "Registrazione Completata!",
    exito_msg: "Abbiamo ricevuto le tue informazioni. La tua camera sarà pronta prima del tuo arrivo.",
    codigo_reserva: "Codice di Prenotazione",
    contactar_hotel: "Contatta l'Hotel su WhatsApp",
    adulto: "Adulto",
    nino: "Bambino",
    whatsapp: "WhatsApp",
    wechat: "WeChat",
    llamada: "Chiamata",
    soroche_titulo: "Consiglio sul Mal di Montagna",
    soroche_msg: "Cusco si trova a 3.399 metri di altitudine. Consigliamo di riposare nelle prime ore, idratarsi con il nostro tè di coca e evitare pasti pesanti.",
  }
};

// ── Detectar idioma automáticamente ──────────────────────────
function detectarIdioma() {
  // 1. Ver si viene en la URL (?lang=en)
  const paramLang = new URLSearchParams(window.location.search).get("lang");
  if (paramLang && TRADUCCIONES[paramLang]) return paramLang;

  // 2. Idioma del navegador
  const navLang = (navigator.language || navigator.userLanguage || "es").substring(0, 2).toLowerCase();
  if (TRADUCCIONES[navLang]) return navLang;

  // 3. Por defecto español
  return "es";
}

// ── Obtener texto traducido ────────────────────────────────
const IDIOMA = detectarIdioma();
function t(clave) {
  return (TRADUCCIONES[IDIOMA] && TRADUCCIONES[IDIOMA][clave]) ||
         (TRADUCCIONES["es"] && TRADUCCIONES["es"][clave]) || clave;
}

// ── Aplicar idioma al HTML (data-i18n) ────────────────────
function aplicarIdioma() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const clave = el.getAttribute("data-i18n");
    el.textContent = t(clave);
  });
  document.querySelectorAll("[data-i18n-ph]").forEach(el => {
    el.placeholder = t(el.getAttribute("data-i18n-ph"));
  });
  // Cambiar lang del HTML
  document.documentElement.lang = IDIOMA;
}
